### PR TITLE
Remove support for Debian Stretch

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This pull request drops support for Debian Stretch.

## 💭 Motivation and context ##

Since Long Term Support has ended and the only remaining support is a commercial offering it does not make sense to continue to support this platform if we are not using it ourselves.

### ⚠ Note ###

This change can only be merged once the [cisagov/cyhy_amis@improvement/update_debian_versions](https://github.com/cisagov/cyhy_amis/tree/improvement/update_debian_versions) branch has been merged (still pending a pull request right now). That project is the only place currently using Debian Stretch in our portfolio.

## 🧪 Testing ##

Automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — CHANGES_REQUESTED** [review]
The `ansible_python_interpreter` jazz under the `provisioner` section in both `molecule-with-systemd.yml` and `molecule-no-systemd.yml` can also be removed with these changes.

**Review by dav3r — APPROVED** [review]
👍 👍

**Review by jsf9k — APPROVED** [review]

**Review by jsf9k — APPROVED** [review]

**Comment by jsf9k** [comment]
Debian appears to have removed the package repositories for Debian Stretch, so I think this PR has to proceed regardless of the status of the [cisagov/cyhy_amis@improvement/update_debian_versions](https://github.com/cisagov/cyhy_amis/tree/improvement/update_debian_versions) branch.

**Comment by mcdonnnj** [comment]
> 

We missed this apparently: https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html

**Comment by mcdonnnj** [comment]
Tests are currently failing because this branch needs the changes in https://github.com/cisagov/skeleton-ansible-role/pull/139. Otherwise it _should_ be good to go given the archival of Debian Stretch packages.

**Comment by mcdonnnj** [comment]
Tests are currently failing because this branch needs the changes in https://github.com/cisagov/skeleton-ansible-role/pull/139. Otherwise it _should_ be good to go given the archival of Debian Stretch packages.

**Review by jsf9k — APPROVED** [review]
_Approval intensifies..._

**Pull request merged**
