### PR TITLE
Prefer the long form of a CLI option

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request modifies a command in a script to use the long form of a CLI option.

## 💭 Motivation and context ##

We generally prefer the long form in scripts because it makes it easier for the reader to follow along if he or she does not possess an encyclopedic knowledge of the tool being used.

## 🧪 Testing ##

- Automated tests pass.
- I ran these changes locally and confirmed that they functioned as expected.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Review by dav3r — CHANGES_REQUESTED** [review]
Sorry hoss, but on MacOS, `xargs` does not support the long form of that option.
See https://www.unix.com/man-page/osx/1/xargs/.

On my Mac:
```
❱ cat foo.txt | xargs --max-args 1 echo
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements] [-S replsize]]
             [-J replstr] [-L number] [-n number [-x]] [-P maxprocs]
             [-s size] [utility [argument ...]]
```

**Comment by jsf9k** [comment]
> Sorry hoss, but on MacOS, `xargs` does not support the long form of that option. See https://www.unix.com/man-page/osx/1/xargs/.
> 
> On my Mac:
> 
> ```
> ❱ cat foo.txt | xargs --max-args 1 echo
> xargs: illegal option -- -
> usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements] [-S replsize]]
>              [-J replstr] [-L number] [-n number [-x]] [-P maxprocs]
>              [-s size] [utility [argument ...]]
> ```

What about the `xargs` available from Brew, RumHole, Boozer, or whatever it is called these days?

**Comment by jsf9k** [comment]
> > Sorry hoss, but on MacOS, `xargs` does not support the long form of that option. See https://www.unix.com/man-page/osx/1/xargs/.
> > On my Mac:
> > ```
> > ❱ cat foo.txt | xargs --max-args 1 echo
> > xargs: illegal option -- -
> > usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements] [-S replsize]]
> >              [-J replstr] [-L number] [-n number [-x]] [-P maxprocs]
> >              [-s size] [utility [argument ...]]
> > ```
> 
> What about the `xargs` available from Brew, RumHole, Boozer, or whatever it is called these days?

The `xargs` functionality is available via the `findutils` package from Brew, but the function has been renamed `gxargs`.  I will create a new PR that adds a comment explaining why we cannot use the long form of the option in this case. :disappointed: :cry:

**Pull request closed without merging**
