### PR TITLE
Always use systemd-enabled Docker images

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request modifies the Molecule configuration of the `default` scenario to always use systemd-enabled Docker images.

## 💭 Motivation and context ##

@mcdonnnj pointed out that is it silly to support both systemd-enabled and systemd-disabled Docker images.  This is because, even if an Ansible role does not make use of systemd it can still be tested under systemd; in fact, doing so is a more realistic test of an actual running system.

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by jsf9k** [comment]
I marked this pull request as blocked because I want to merge it separately from the main Kraken.  This is a big change, and handling it individually will help to ensure mistakes are not made.

**Review by dv4harr10 — APPROVED** [review]

**Review by michaelsaki — COMMENTED** [review]
@jsf9k Should the following lines be changed since we are removing `molecule-no-systemd.yml`?

https://github.com/cisagov/skeleton-ansible-role/blob/292b0c340cb1cdcc703cf1632161cde9aa206749/molecule/default/molecule.yml#L3-L4

**Comment by jsf9k** [comment]
> @jsf9k Should the following lines be changed since we are removing `molecule-no-systemd.yml`?
> 
> https://github.com/cisagov/skeleton-ansible-role/blob/292b0c340cb1cdcc703cf1632161cde9aa206749/molecule/default/molecule.yml#L3-L4

Great catch!  Please see commit 02e1530.

**Review by michaelsaki — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
Makes sense, let's do it! 👍

**Review by mcdonnnj — APPROVED** [review]
:godmode: :shipit:

**Comment by jsf9k** [comment]
I guess this PR wasn't `blocked` after all!  :sweat_smile:

**Pull request merged**
