### PR TITLE
Add support for Debian Trixie

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

Add support for Debian Trixie.  Also switch to using [geerlingguy/docker-debian12-ansible](https://github.com/geerlingguy/docker-debian12-ansible) now that it exists.

## 💭 Motivation and context ##

Debian Bookworm dropped in June, so we need to start testing on Trixie.

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
🦖E 🎉

**Review by dv4harr10 — APPROVED** [review]

**Comment by mcdonnnj** [comment]
@jsf9k https://github.com/ansible/ansible-lint/pull/3841 has been merged and once a new version is cut (and our pre-commit configuration updated) we should be able to finish this pull request.

**Comment by jsf9k** [comment]
> @jsf9k [ansible/ansible-lint#3841](https://github.com/ansible/ansible-lint/pull/3841) has been merged and once a new version is cut (and our pre-commit configuration updated) we should be able to finish this pull request.

A new version of `ansible-lint` [has been released](https://github.com/ansible/ansible-lint/releases/tag/v6.21.0).  I have uncommented Trixie in the metadata file and force pushed.

**Comment by jsf9k** [comment]
Well it worked on my local machine, but it didn't work here even after I blew away the cache.  I guess I will try again in a day or so. :cry:

**Comment by mcdonnnj** [comment]
> Well it worked on my local machine, but it didn't work here even after I blew away the cache. I guess I will try again in a day or so. 😢

@jsf9k The pre-commit hook version has to be bumped and I assume you're not doing that in this PR as it should trickle down from [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic). Please see https://github.com/cisagov/skeleton-ansible-role/actions/runs/6565455910 for an Action run with the new hook version in effect however.

**Pull request merged**
