### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-generic.git`](https://github.com/cisagov/skeleton-generic.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
⚡ 
I will merge this PR when approved and then merge https://github.com/cisagov/skeleton-ansible-role/pull/53 shortly afterwards so that downstream lineage PRs will include both changes.

**Review by jsf9k — APPROVED** [review]
:zap:

**Review by mcdonnnj — CHANGES_REQUESTED** [review]
The `test` job in `.github/worksflows/build.yml` needs to updated in the same way the `lint` job was upstream.

**Comment by dav3r** [comment]
> The `test` job in `.github/worksflows/build.yml` needs to updated in the same way the `lint` job was upstream.

Great catch!  Please take a look at https://github.com/cisagov/skeleton-ansible-role/pull/54/commits/0519e8bd000b407a5e2f2cc69840c08a6dccdd11.

**Review by mcdonnnj — APPROVED** [review]
Thanks for adding that change 👍 LGTM ✔️

**Pull request merged**
