### PR TITLE
Remove unnecessary Ansible configuration option

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request removes the now-unnecessary `force_valid_group_names` Ansible configuration option.

## 💭 Motivation and Context ##

Ansible (as of 2.10) now correctly identifies Kali Linux as the Kali distribution of Debian, so it is no longer necessary to force valid group names.

## 🧪 Testing ##

All `molecule` tests and `pre-commit` hooks pass.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Excellent!  

Do we know which version of Ansible this was fixed in?  I did some searching, but could not find the answer.

**Comment by jsf9k** [comment]
> Do we know which version of Ansible this was fixed in? I did some searching, but could not find the answer.

It's mentioned [here](../blob/develop/meta/main.yml#L9-L14).  I amended the PR description to include it as well.

**Review by mcdonnnj — APPROVED** [review]
Good to get the old band-aids pulled off! @dav3r I believe this PR resolved it: https://github.com/ansible/ansible/pull/69194, and as @jsf9k mentioned it was rolled out with version `2.10`.

**Review by hillaryj — APPROVED** [review]
🏆

**Pull request merged**
