### PR TITLE
Add Kali Linux as a platform in the role metadata

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

Update the role's metadata to list Kali as a platform with the latest release year as the supported version. The comment explaining the relationship between Kali Linux and Debian Bookworm is removed.

## 💭 Motivation and context ##

With the addition of Kali as a platform on Ansible Galaxy per https://github.com/ansible/galaxy/issues/3059#issuecomment-1513453476 (and verified [against the API](https://galaxy.ansible.com/api/v1/platforms/?search=Kali)) it makes sense to update our role metadata.

## 🧪 Testing ##

Automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
👍 👍

**Review by dv4harr10 — COMMENTED** [review]
I see the change logged here under the files changed tab for review changes; however, I don't notice the same via code/meta/main.yml where Kali linux is being made an option. Question is should Kali linux be an option there? Also, in the Ansible-lint file 2 commented links on line 2 and line 7 return 404 errors.  Also, labels.yml file the kraken emoji image can be seen as a special character and cause processing error.

**Comment by jsf9k** [comment]
> I see the change logged here under the files changed tab for review changes; however, I don't notice the same via code/meta/main.yml where Kali linux is being made an option. Question is should Kali linux be an option there?

@dv4harr10 - I don't follow what you are saying.  The addition of Kali Linux in `meta/main.yml` is the _only_ change in this PR, but you seem to be saying that you cannot see it.  I think I am missing something.

**Comment by jsf9k** [comment]
> Also, labels.yml file the kraken emoji image can be seen as a special character and cause processing error.

The `labels.yml` file is a UTF-8 file, and hence it can safely contain _any_ valid UTF-8 characters (including emojis).  So if I understand what you are saying then this isn't really an issue.  In any event, this isn't something that really applies to the changes in this particular PR, so if you still think it is valid then please create a new issue in [this repository](https://github.com/cisagov/skeleton-generic).

**Comment by jsf9k** [comment]
> in the Ansible-lint file 2 commented links on line 2 and line 7 return 404 errors

Good catch, @dv4harr10!  That isn't something that really applies to the changes in this particular PR, though.  Could you create a new issue in this repository for this?

**Comment by jmorrowomni** [comment]
> > in the Ansible-lint file 2 commented links on line 2 and line 7 return 404 errors
> 
> Good catch, @dv4harr10! That isn't something that really applies to the changes in this particular PR, though. Could you create a new issue in this repository for this?

It looks like those actually come from skeleton-generic, so that's the repo the issue should probably be opened in

**Comment by jsf9k** [comment]
> > > in the Ansible-lint file 2 commented links on line 2 and line 7 return 404 errors
> > 
> > 
> > Good catch, @dv4harr10! That isn't something that really applies to the changes in this particular PR, though. Could you create a new issue in this repository for this?
> 
> It looks like those actually come from skeleton-generic, so that's the repo the issue should probably be opened in

Ah, you are correct @jmorrowomni!

**Comment by dv4harr10** [comment]
in the Ansible-lint file 2 commented links on line 2 and line 7 return 404 errors.  It appears that 

https://ansible-lint.readthedocs.io/en/latest/configuring/ should be https://ansible-lint.readthedocs.io/configuring/

and,
https://ansible-lint.readthedocs.io/en/latest/rules/ should be https://ansible-lint.readthedocs.io/rules/

**Comment by jsf9k** [comment]
> in the Ansible-lint file 2 commented links on line 2 and line 7 return 404 errors. It appears that
> 
> https://ansible-lint.readthedocs.io/en/latest/configuring/ should be https://ansible-lint.readthedocs.io/configuring/
> 
> and, https://ansible-lint.readthedocs.io/en/latest/rules/ should be https://ansible-lint.readthedocs.io/rules/

Please see cisagov/skeleton-generic#131 and cisagov/skeleton-generic#132.

**Review by dv4harr10 — APPROVED** [review]

**Pull request merged**
