### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-generic.git`](https://github.com/cisagov/skeleton-generic.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

## ✅ Pre-approval checklist ##

Remove any of the following that do not apply. If you're unsure about
any of these, don't hesitate to ask. We're here to help!

- [x] All relevant type-of-change labels have been added.
- [x] All new and existing tests pass.

---

> **Note**
> You are seeing this because one of this repository's maintainers has
> configured [Lineage] to open pull requests.

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by mcdonnnj** [comment]
Please note that I cherry-picked from #143 to pass tests (and this PR will thus supersede that PR). I also wanted to open discussion about ignoring the following ansible-lint rules that I came across in [cisagov/cyhy_amis](https://github.com/cisagov/cyhy_amis) that would be good to make a decision on for all of our Ansible projects:
- [`package-latest`](https://ansible-lint.readthedocs.io/rules/package-latest/)
- [`var-naming[no-role-prefix]`](https://ansible-lint.readthedocs.io/rules/var-naming/)

> **Note**
> The next one is just for awareness when resolving downstream PRs later.

Also the following rules appear have been changed as I saw hits for them when checking against a selection of our roles:
- [`no-changed-when`](https://ansible-lint.readthedocs.io/rules/no-changed-when/)

**Comment by jsf9k** [comment]
Re `var-naming[no-role-prefix]`, I think satisfying the linter is annoying, but a good idea.  Role vars can have playbook-wide scope if included via a `roles:` block.

The Ansible documentation indicates that this is also the case when roles are included via `include_role`, but disturbingly I have not found that to be the case.

I think I like the `package-latest` and `no-changed-when` rules as well.  Don't fight the linter!

**Comment by mcdonnnj** [comment]
> Re `var-naming[no-role-prefix]`, I think satisfying the linter is annoying, but a good idea. Role vars can have playbook-wide scope if included via a `roles:` block.
> 
> The Ansible documentation indicates that this is also the case when roles are included via `include_role`, but disturbingly I have not found that to be the case.
> 
> I think I like the `package-latest` and `no-changed-when` rules as well. Don't fight the linter!

Sorry the `no-changed-when` was just a heads up and was not meant to be a question about disabling. I added a note to clarify that in my original comment. The only reason I mentioned `package-latest` is I ran into wrestling against it when trying to make sure that a possibly installed package was using the version from backports. With the rule in place I would need to either specify the version from backports to install or make sure it was uninstalled before attempting to install from backports (either of which is fine and just a slight annoyance at worst).

**Comment by dav3r** [comment]
If you are both on board with ensuring we comply with [`package-latest`](https://ansible-lint.readthedocs.io/rules/package-latest/) and [`var-naming[no-role-prefix]`](https://ansible-lint.readthedocs.io/rules/var-naming/), then I am as well.

**Comment by jsf9k** [comment]
> The only reason I mentioned `package-latest` is I ran into wrestling against it when trying to make sure that a possibly installed package was using the version from backports. With the rule in place I would need to either specify the version from backports to install or make sure it was uninstalled before attempting to install from backports (either of which is fine and just a slight annoyance at worst).

Could you simply add an ignore directive to that task, similar to what we do [here](https://github.com/cisagov/ansible-role-upgrade/blob/75a0ae8049741179e3309843d917d106a21b68af/tasks/dnf.yml#L8)?

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]

**Comment by mcdonnnj** [comment]
> > The only reason I mentioned `package-latest` is I ran into wrestling against it when trying to make sure that a possibly installed package was using the version from backports. With the rule in place I would need to either specify the version from backports to install or make sure it was uninstalled before attempting to install from backports (either of which is fine and just a slight annoyance at worst).
> 
> Could you simply add an ignore directive to that task, similar to what we do [here](https://github.com/cisagov/ansible-role-upgrade/blob/75a0ae8049741179e3309843d917d106a21b68af/tasks/dnf.yml#L8)?

Yes, sorry, I wasn't intending to make a mountain out of a mole hill. I prefer to abide by the linter rules if we're using them when possible, and since the backports version is unlikely to change I'm just planning on providing a version pin.

**Pull request merged**
